# This file was initially generated by terraspace_plugin_aws 0.6.1
# Backend Config Variables Docs
# https://terraspace.cloud/docs/config/backend/variables/
<% if ENV["AZURERM"] %>
terraform {
  backend "azurerm" {
    resource_group_name  = "<%= expansion(':APP-:ENV-:LOCATION', expansion: "azurerm") %>"
    storage_account_name = "<%= expansion('ts:APP_HASH:SUBSCRIPTION_HASH:LOCATION_HASH:ENV', backend: "azurerm") %>"
    container_name       = "tofu-state"
    key                  = "<%= expansion(':PROJECT/:TYPE_DIR/:APP/:ROLE/:MOD_NAME/:ENV/:EXTRA/:LOCATION/tofu.tfstate', backend: "azurerm") %>"
  }
}
<% elsif ENV["AWS"] %> 
terraform {
  backend "s3" {
    bucket         = "<%= expansion('ts-:ACCOUNT-:REGION-:END', backend: "s3") %>"
    key            = "<%= expansion(':PROJECT/:TYPE_DIR/:APP/:ROLE/:MOD_NAME/:ENV/:EXTRA/:REGION/tofu.tfstate', backend: "s3") %>"
    region         = "<%= expansion('', backend: "s3") %>"
    encrypt        = true
    dynamodb_table = "terraform_locks"
  }
}
<% elsif ENV["GCP_BACKEND"] %>
terraform {
  backend "gcs" {
    bucket = "<%= expansion('ts-:PROJECT-:REGION-:ENV', backend: "gcs") %>"
    prefix = "<%= expansion(':PROJECT/:TYPE_DIR/:APP/:ROLE/:MOD_NAME/:ENV/:EXTRA/:REGION', backend: "gcs") %>"
  }
}
<% else %>
# This is where you put your backend declaration. Example:
#
# terraform {
#   backend "local" {
#     path = "terraform.tfstate"
#   }
# }
#
# More examples: https://terraspace.cloud/docs/config/backend/examples/
#
<% end %>
